import os

TENCENT_SECRET_ID = os.getenv("TENCENT_SECRET_ID_CN")
TENCENT_SECRET_KEY = os.getenv("TENCENT_SECRET_KEY_CN")

LEANCLOUD_APP_ID = os.getenv("LEANCLOUD_APP_ID")
LEANCLOUD_APP_KEY = os.getenv("LEANCLOUD_APP_KEY")
LEANCLOUD_MASTER_KEY = os.getenv("LEANCLOUD_MASTER_KEY")  # optional, for admin operations